### ISSUE TITLE
哥，麻烦更新一下好么，跪求。

### ISSUE THREAD

**Issue by kk20180123** [the-eric-kwok/Convertible_Bond_Monitor#3]
iOS15.1运行错误，麻烦您更新一下，这个真的好好用啊。跪求跪求。

**Comment by the-eric-kwok** [comment]
#2 是你发的不？

**Comment by kk20180123** [comment]
> #2 是你发的不？

什么？麻烦您更新一下？

**Comment by the-eric-kwok** [comment]
我从未承诺过在 iOS15 自动化上运行这个 python 脚本，你说需要更新的是我写的快捷指令吗？

**Comment by kk20180123** [comment]
> 我从未承诺过在 iOS15 自动化上运行这个 python 脚本，你说需要更新的是我写的快捷指令吗？

那要么就是别人搬运你的脚本了，捷径用着还不错，那大佬您有可能出个捷径么？哈哈。或者圈X也行。有没有这种可能。😅😅😅

**Comment by kk20180123** [comment]
![image](https://user-images.githubusercontent.com/76581611/142802991-c074c26d-25c6-455b-bbee-1b7a14dbfcd4.jpeg)



这里是您这里的地址。所以我才联系您的。

**Comment by the-eric-kwok** [comment]
抱歉，最近太忙，没有办法抽出时间来完善。作为一个 work around，你可以尝试用「捷径盒」这款应用，把此仓库中的 python3 代码复制进去执行。

**Comment by the-eric-kwok** [comment]
适用于 Pyto 的脚本：
https://www.icloud.com.cn/iclouddrive/0NStxSH_H4KkPjalaZi7MGqyg

我测试了一下，使用 Pyto 这款软件可以运行，你需要前往 [sct.ftqq.com](https://sct.ftqq.com) 开通一个send key，并且填入脚本开头的`__SendKey` 参数中，这样才能启用微信推送的功能。因为时间关系我没有适配 Pyto 的通知功能，希望你理解。

**Comment by kk20180123** [comment]
> 抱歉，最近太忙，没有办法抽出时间来完善。作为一个 work around，你可以尝试用「捷径盒」这款应用，把此仓库中的 python3 代码复制进去执行。




谢谢，谢谢。多有打扰，请您勿怪。
我研究研究，再次感谢。

**Comment by kk20180123** [comment]
> 抱歉，最近太忙，没有办法抽出时间来完善。作为一个 work around，你可以尝试用「捷径盒」这款应用，把此仓库中的 python3 代码复制进去执行。



那，哥，您有时间了麻烦维护一下呗。好么？先不打扰您了。怪不好意思的。

**Comment by kk20180123** [comment]
> 适用于 Pyto 的脚本：
> https://www.icloud.com.cn/iclouddrive/0NStxSH_H4KkPjalaZi7MGqyg
> 
> 我测试了一下，使用 Pyto 这款软件可以运行，你需要前往 [sct.ftqq.com](https://sct.ftqq.com) 开通一个send key，并且填入脚本开头的`__SendKey` 参数中，这样才能启用微信推送的功能。因为时间关系我没有适配 Pyto 的通知功能，希望你理解。

哥，更新15.2之后就正常了，自动化可以运行了。不延迟了。给您说一声，叨扰了。多有得罪，谢谢好意。

**Comment by the-eric-kwok** [comment]
👌
