### ISSUE TITLE
哥。跪求您。

### ISSUE THREAD

**Issue by kk20180123** [the-eric-kwok/Convertible_Bond_Monitor#5]
麻烦您再给我共享一下那个可转债py脚本文件。上次那个找不到了，之前您共享过一次，我不知道存在哪里了。就是那个可转债推送的py脚本，直接在手机的运行，不用什么依赖啥的。麻烦您。

再次恳求您。

**Comment by the-eric-kwok** [comment]
可以使用[这个快捷指令](https://sharecuts.cn/shortcut/9749)
